name: Update forks

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main

jobs:
  update_forks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run shell script
      run: |
        #!/bin/bash

        # read the contents of forks.txt into an array
        readarray -t urls < forks.txt

        # initialize an empty array to store the sorted data
        declare -a sorted

        # loop through the urls
        for url in "${urls[@]}"; do
          # get the version number
          version=$(curl -s "${url}/version.txt" 2> /dev/null || echo "0.0.0")

          # add the url and version to the sorted array
          sorted+=("$version $url")
        done

        # sort the sorted array by version and then alphabetically
        IFS=$'\n' sorted=($(sort -V <<<"${sorted[*]}"))

        # write the sorted array to sorted.txt
        printf "%s\n" "${sorted[@]}" > sorted.txt
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: sorted.txt
        path: sorted.txt
        
    - name: Debugging
      run: |
        echo "Current working directory: $(pwd)"
        ls -al
