name: Update forks

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main

jobs:
  update_forks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run shell script
      run: |
        #!/bin/bash

        # read the contents of forks.txt into an array
        readarray -t urls < forks.txt

        # initialize an empty array to store the sorted data
        declare -a sorted

        # loop through the urls
        for url in "${urls[@]}"; do
          # get the version number
          version=$(curl -s "${url}/version.txt" 2> /dev/null | grep -Eo '[0-9]+\.[0-9]+\.[0-9]+')

          # default to 0.0.0 if the version is not found
          if [ -z "$version" ]; then
            version="0.0.0"
          fi
          # add the url and version to the sorted array
          sorted+=("$version $url")
        done

        # sort the sorted array by version and then alphabetically
        IFS=$'\n' sorted=($(sort -V <<<"${sorted[*]}"))

        # write the sorted array to sorted.txt
        printf "%s\n" "${sorted[@]}" > sorted.txt
        
    - name: Push changes
      run:
        git config user.email "github-actions"
        git config user.name "Github Actions"
        git add sorted.txt
        git commit -m "sorted forks"
        git push
        
    - name: Debugging
      run: |
        echo "Current working directory: $(pwd)"
        ls -al
