name: Update forks

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main

jobs:
  update_forks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Get latest version of each fork
      run: |
        while IFS='' read -r line || [[ -n "$line" ]]; do
        version=$(curl -sL $line/version.txt | grep -Eo '^[0-9]+\.[0-9]+\.[0-9]+')
        if [ $? -eq 0 ]; then
          echo "$version $line" >> temp_forks.txt
        else
          echo "" >> temp_forks.txt
        fi
        done < forks.txt
      
    - name: Sort forks by version number
      run: |
        sort -V temp_forks.txt > sorted_forks.txt
        mv sorted_forks.txt forks.txt
        rm temp_forks.txt
        
    - name: Commit and push changes
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add forks.txt
        git commit -m "sorted"
        git push
